name: CI/CD

on:
  push:
    branches: 
      - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
          
      - name: Install Vercel
        run: sudo npm i -g vercel
        env:
            VERCEL_ORG_ID: '{{ secrets.VERCEL_ORG_ID }}'
            VERCEL_PROJECT_ID: '{{ secrets.VERCEL_PROJECT_ID }}'        
        
      - name: Deploy vercel
        run: vercel --token {{ secrets.VERCEL_TOKEN }}


